name: flutter_application
description: "A new Flutter project."

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3

  url_launcher: ^6.2.1

  intl: ^0.18.1

  provider: ^6.1.1

  flutter_svg: ^2.2.0

  cupertino_icons: ^1.0.8

  google_fonts: ^6.1.0

  http: ^1.4.0
  flutter_inner_shadow: ^0.0.1

  pin_code_fields: ^8.0.0

  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: "Rounded"
      fonts:
        - asset: assets/fonts/sfProRounded/SF-Pro-Rounded-Bold.otf
        - asset: assets/fonts/sfProRounded/SF-Pro-Rounded-Semibold.otf
        - asset: assets/fonts/sfProRounded/SF-Pro-Rounded-Ultralight.otf
        - asset: assets/fonts/sfProRounded/SF-Pro-Rounded-Medium.otf
        - asset: assets/fonts/sfProRounded/SF-Pro-Rounded-Regular.otf
        - asset: assets/fonts/sfProRounded/SF-Pro-Rounded-Thin.otf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
